### ISSUE TITLE
Due date of some cards that I reviewed today are 3-22-1955 [BUG]

### ISSUE THREAD

**Issue by shmuelsash** [open-spaced-repetition/fsrs4anki#207] opened 2023-04-10 02:44 UTC
There's something wrong with the scheduler as some of my cards due date is completely messed up even after I run the FSRSHelper is doesn't fix anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/35056305/230815058-0b179f18-dc75-437e-9dfa-0e505aa5c117.png)
![image](https://user-images.githubusercontent.com/35056305/230815097-32680e51-fce5-4731-8a1d-1280daffdfef.png)

**Environment**
 - Anki version: Version ⁨2.1.60 (76d88073)⁩ ; Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
 - OS: Windows & I use Ankidroid with FSRS4Anki Helper
 - Scheduler version: v3.14.3
 - Optimizer version: not sure - ran it a few days ago

**Additional context**
Many of these cards are in a filtered deck that of overdue cards, could that be the issue?

**Comment by L-M-Sherlock** [comment] 2023-04-10 02:52
Is it caused by scheduler or the helper?

**Comment by shmuelsash** [comment] 2023-04-10 02:53
I don't know but the Helper isn't fixing it

How can I check?

**Comment by L-M-Sherlock** [comment] 2023-04-10 02:58
Did this problem happen before you used the helper today？

**Comment by shmuelsash** [comment] 2023-04-10 02:58
Here's another one
I did this card today, I think it was done on Ankidroid
![image](https://user-images.githubusercontent.com/35056305/230816508-466b1e61-65f4-4578-ac04-57eed44835f8.png)

**Comment by shmuelsash** [comment] 2023-04-10 02:58
> Did this problem happen before you used the helper today？

Never noticed it

**Comment by shmuelsash** [comment] 2023-04-10 03:01
Sure
I should post it here?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:10
Do you have the backup file that stored before you reschedule all cards?

**Comment by shmuelsash** [comment] 2023-04-10 03:12
Yes

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:13
I need the backup file to reproduce this bug.

**Comment by shmuelsash** [comment] 2023-04-10 03:13
I'm uploading all my backup files; ETA 15 mins

**Comment by shmuelsash** [comment] 2023-04-10 03:16
Nevermind here you go
https://wormhole.app/75or4#UuMJ5mGSX93O802m3qB2Nw

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:20
So many backup files. Which one was stored after you synced from AnkiDroid?

**Comment by shmuelsash** [comment] 2023-04-10 03:20
I synced a few times today so its gotta be in the files from today

**Comment by shmuelsash** [comment] 2023-04-10 03:22
Try this one first "backup-2023-04-09-21.28.23.colpkg"

I noticed something after syncing then

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:26
I found that some cards' due are wrong even in the "backup-2023-04-09-21.28.23.colpkg".

<img width="542" alt="image" src="https://user-images.githubusercontent.com/32575846/230819446-1f6bdf9f-a7d1-4241-8ee6-8410ca8be4bb.png">

**Comment by shmuelsash** [comment] 2023-04-10 03:27
Do you see it in "backup-2023-04-09-18.45.51.colpkg" bec I have a feeling it occurred between these 2

**Comment by shmuelsash** [comment] 2023-04-10 03:29
My next hunch, if its not from between those 2 is between "backup-2023-04-05-19.06.02.colpkg" & "backup-2023-04-08-21.15.12.colpkg" (or another one from earlier on in the evening of 4/08)

Bec I did have an issue then where Anki had to recover some cards, I'm wondering now if that's what causes this

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:32
I also checked them, and they all have some incorrect cards. I found that the due is correct in `backup-2023-03-31-18.21.17.colpkg`.

**Comment by shmuelsash** [comment] 2023-04-10 03:33
Oh wow, so then I have no idea what the issue could be from

Could it be from when I re-ran the optimizer?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:34
Is it caused by FSRS? Do you use any other add-ons?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:35
Here is the screenshot of `backup-2023-04-05-19.06.02.colpkg`.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/32575846/230820518-69b2bd70-9aad-432e-b4a7-58a1adf62bef.png">

**Comment by shmuelsash** [comment] 2023-04-10 03:36
I use a bunch but none that reschedule besides for FSRS (and the straight rewards)

**Comment by shmuelsash** [comment] 2023-04-10 03:36
> Here is the screenshot of `backup-2023-04-05-19.06.02.colpkg`.
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/32575846/230820518-69b2bd70-9aad-432e-b4a7-58a1adf62bef.png">

What am I looking at here?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:37
> recover some cards

I reproduce this. After I check database, the due are incorrect.

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:38
> What am I looking at here?

I open `backup-2023-04-05-19.06.02.colpkg` and view the card browser.

**Comment by shmuelsash** [comment] 2023-04-10 03:40
So you're saying that the recovery is what caused the issue?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:40
What caused the database problem? Did the FSRS add-on do that?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:40
> So you're saying that the recovery is what caused the issue?

Yep

**Comment by shmuelsash** [comment] 2023-04-10 03:40
No
That database problem was caused by Ankidroid rebuilding a filtered deck

**Comment by shmuelsash** [comment] 2023-04-10 03:41
> > So you're saying that the recovery is what caused the issue?
> 
> Yep

So what can I do?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:41
Sorry for that, but it could not be fixed by the helper add-on. Maybe you need to report it in https://forums.ankiweb.net/

**Comment by shmuelsash** [comment] 2023-04-10 03:43
What would happen if I continued to use the deck this way? Would the addon eventually figure out the correct due date?

**Comment by L-M-Sherlock** [comment] 2023-04-10 03:46
The helper add-on modify the card's due based on its original due. The result will be incorrect if the original due is incorrect.

**Comment by shmuelsash** [comment] 2023-04-10 03:50
I see

**Closed** 2023-04-10 06:41 UTC
Labels: bug
