### ISSUE TITLE
[Question] Compatibility with Add-on "Learn now & Grade now" (Documentation)

### ISSUE THREAD

**Issue by Exponent4806** [open-spaced-repetition/fsrs4anki#540] opened 2023-11-21 10:10 UTC
**Research**

*Enter an [x] character to confirm the points below:*

- [ x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x ] I have searched for similar existing questions here

**Problem Description**

The Add-on "[Learn Now & Grade Now](https://ankiweb.net/shared/info/1021636467)" seems at least partially compatible with FSRS. However, I am not completely sure, and it is missing in the list of _"compatible add-ons"_ on GitHub.

That add-on has 2 functions:
1) Learn Now
2) Grade Now

![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/121114125/0e226776-edc2-4e47-a4d9-9a60c6f1c5e9)

The Grade Now function (2) is useful to **manually** fail a card if one finds a word/concept outside Anki and is unable to remember it.  I have been using it for months without any issues apparently.

However, I used recently the function "Learn Now" (1) and it messed up my deck. I had no more cards to review within a week and the FSRS algorithm seemed to be disrupted.

**Questions**
* Could you please kindly check this compatibility "issue" @L-M-Sherlock  ?

* It would be helpful to add the "Learn now & Grade now" in the list of _"compatible Add-ons"_ _(either yes, no or partially compatible)._

**Comment by Exponent4806** [comment] 2023-11-21 11:39
_> 8. Please mention that no add-ons that modify cards' intervals or Ease should be used when FSRS is enabled._ https://github.com/open-spaced-repetition/fsrs4anki/issues/486#issuecomment-1818889586

The Add-on "Learn now & Grade Now" only "fails" a card via the browser exactly as if the card would have been seen.  Is that correct **Tatsumoto** ?

The problem seems to lie in the **"learn now"** function. After using it, the schedule with FSRS was simply wrong...  :sob:

**Comment by Expertium** [comment] 2023-11-21 11:47
While I don't advise using any add-ons that affect scheduling with FSRS, @L-M-Sherlock, please check compatibility of this add-on.

**Comment by tatsumoto-ren** [comment] 2023-11-21 23:39
> I used recently the function "Learn Now" (1) and it messed up my deck. 

What happened exactly?

"Learn now" doesn't do anything special, it simply changes the card's queue and type (and a few less significant parameters).  See [here](https://github.com/Ajatt-Tools/learn-now-button/blob/e75edcf81eecc473a019dd3403797f4b46e78b3c/learn_now.py#L89).

But I don't use fsrs and can't say anything about whether the add-on is compatible with fsrs.

**Comment by L-M-Sherlock** [comment] 2023-11-22 02:13
> "Learn now" doesn't do anything special, it simply changes the card's queue and type (and a few less significant parameters)

FSRS will calculate the initial memory state in the first learning when the card is new. If a user changes the card's queue and type, the initialization will be skipped. If the user learns the card, FSRS will calculate the initial memory state via converting the interval and ease of the card. It will mess up the scheduling of cards.

**Comment by L-M-Sherlock** [comment] 2023-11-22 02:22
"Grade now" works with FSRS. The only problem is `Time=0⁩s`.

**Comment by Exponent4806** [comment] 2023-11-22 05:43
> "Grade now" works with FSRS. The only problem is `Time=0⁩s`

Should FSRS users avoid completely using the Add-on ["Learn now & Grade Now" ](https://ankiweb.net/shared/info/1021636467)?

I have been using the "Grade now" function of the add-on during 8 months together with FSRS.

I have not noticed any damage to my collection because I rarely fail cards in such a way. For example, I only fail 2-3 cards per week with the "Learn now" function of the add-on. However, my collection contains 20.000 cards and I do not notice any difference....

_Should the add-on simply be added to the list of "incompatible add-ons" with FSRS?_ :thinking: 

By the way,  thanks for your great work @L-M-Sherlock :1st_place_medal:  Your great contribution to Anki has really improved my life... !

**Comment by L-M-Sherlock** [comment] 2023-11-22 06:15
If you use "Grade now", please avoid to use `Compute optimal retention (experimental)`, because it relies on the time of each ratings.

**Comment by Expertium** [comment] 2023-11-22 13:41
I think it's better to mark this add-on as "incompatible".

**Comment by tatsumoto-ren** [comment] 2023-11-23 03:25
Since it's a bug in FSRS, I think this issue needs to stay open until FSRS becomes compatible with the add-on. Alternatively, we could create a new issue and mark it as a `[Feature Request]`.

**Comment by L-M-Sherlock** [comment] 2023-11-23 03:39
> Since it's a bug in FSRS

I don't think it is a bug in FSRS. Because we couldn't distinguish a card with incomplete revlogs in learning stage and a card which `Learn now`. @dae, what do you think of?

**Comment by tatsumoto-ren** [comment] 2023-11-23 03:56
> FSRS calculates the initial memory state in the first learning when the card is new. 

This is where the possible bug is located. The reason is that you need to calculate the initial memory state when a card graduates. Before it graduates you can't tell anything about its memory state since the data is insufficient.

**Comment by L-M-Sherlock** [comment] 2023-11-23 04:10
> This is where the possible bug is located. The reason is that you need to calculate the initial memory state when a card graduates. Before it graduates you can't tell anything about its memory state since the data is insufficient.

It's intended for FSRS. FSRS just the first rating to initialize the memory state. And the subsequent reviews of the same card will not update the memory state.

**Comment by dae** [comment] 2023-11-23 05:10
There's already code in Anki to infer memory state when it's missing, so I'd expect things to already work. I suggest you start by describing exactly what you mean by "the schedule with FSRS went wrong", and provide us with a set of steps we can take to reproduce the issue you're seeing.

**Comment by L-M-Sherlock** [comment] 2023-11-23 06:06
Normal case:
1. Add a new card
2. Press `Good`

<img width="825" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/cf72d702-58a7-4bb2-a67d-f43ee3369ca6">

Current case:
1. Add a new card
2. Learn Now
3. Press `Good`

<img width="825" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/87aa381f-b280-43a9-9e56-74898c46444a">

The stability are inconsistent.

**Comment by dae** [comment] 2023-11-24 04:40
In the second case, there are no review logs, so Anki is calling fsrs-rs's memory_state_from_sm2(ease_factor=2.5, interval=0, sm2_retention=0.9). So perhaps that function needs adjusting if you think its current outputs for that input are inappropriate?

**Comment by L-M-Sherlock** [comment] 2023-11-24 05:38
I would like to ask @user1823. My initial solution is don't convert from sm2 when the interval is shorter than 1 day (or the revlog is (re)learning), and initialize the memory state from the rating.

**Comment by user1823** [comment] 2023-11-24 11:44
> My initial solution is don't convert from sm2 when the interval is shorter than 1 day (or the revlog is (re)learning), and initialize the memory state from the rating.

I think that the only exception to calling `memory_state_from_sm2` in the event of absence of revlogs should be the case when `ivl = 0`.

The problem with also skipping the other cases where `ivl < 1d` is that we can't know what the previous rating was. Remember that we need to deal with the cases other than the present case (the one resulting from this add-on).

**Comment by L-M-Sherlock** [comment] 2023-11-24 14:30
> I think that the only exception to calling memory_state_from_sm2 in the event of absence of revlogs should be the case when ivl = 0.

So what's your suggestion for dealing with the current issue?

**Comment by user1823** [comment] 2023-11-24 14:34
When `ivl = 0`, don't call `memory_state_from_sm2` and initialize the memory state from the next rating.

This suggestion is based on the assumption that if ivl is less than 1 day ( say, 6 hours), it is not considered to be 0.

**Comment by L-M-Sherlock** [comment] 2023-11-24 15:35
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/32575846/285111540-87aa381f-b280-43a9-9e56-74898c46444a.png">
> The stability are inconsistent.

But in this case, the ivl = 10 minutes.

**Comment by user1823** [comment] 2023-11-24 15:42
If I have understood it correctly, in this case, Anki will call memory_state_from_sm2 before the rating seen in the card info. At that time, ivl = 0 and that's the main issue here.

**Comment by L-M-Sherlock** [comment] 2023-11-25 06:55
> Anki will call memory_state_from_sm2 **before** the rating seen in the card info.

Here is the relevant code: https://github.com/ankitects/anki/blob/046ae539fb4bf266a408986e2cf71c5730759607/rslib/src/scheduler/fsrs/memory_state.rs#L253-L269

I will dive into it later.

**Comment by user1823** [comment] 2023-11-25 08:17
I guess that the issue can be fixed by changing line  163 of the above-mentioned file to:

```rs
if self.ctype == CardType::New or self.interval == 0 {
```

**Comment by dae** [comment] 2023-11-25 09:50
I am ok with merging https://github.com/ankitects/anki/pull/2849 in, but is it the best solution? It's relying on the add-on to set the interval to 0 and not 1. And should a card with a non-zero interval and no review history/ease 2.5 be given a difficulty of 84%?

**Comment by user1823** [comment] 2023-11-25 10:01
> It's relying on the add-on to set the interval to 0 and not 1. 

With that patch, we are basically adding a way to deal with the case where ivl = 0 regardless of how the card got that interval. FSRS can't extract any meaningful information from such card anyway.

> And should a card with a non-zero interval and no review history/ease 2.5 be given a difficulty of 84%?

Technically, that is a separate issue and I was planning to give some more thought. But first, can you tell me what value for `ivl` is used in `memory_state_from_sm2` when the interval is, say, 10 min? Is it 0.007 day?

**Comment by L-M-Sherlock** [comment] 2023-11-25 10:26
> Technically, that is a separate issue and I was planning to give some more thought. But first, can you tell me what value for ivl is used in memory_state_from_sm2 when the interval is, say, 10 min? Is it 0.007 day?

It's zero. And FSRS clamps it to 0.1 day.

**Comment by user1823** [comment] 2023-11-25 10:53
I thought about the issue in depth. I can't think of any good way to solve the following problem.

> The problem with also skipping the other cases where ivl < 1d is that we can't know what the initial rating was.

So, I think that the best we can do is to assume that the user failed that card on that day and that failed review was the first review of the card (otherwise we will have to find a value of previous stability).

So, when inferring states during review, if calc_S < w[0], take S = w[0] and D = w[4] + 2 * w[5]. Then, the review shouldn't update the memory states because FSRS (currently) doesn't consider same-day reviews.

Here, calc_S is the interval calculated by memory_state_from_sm2 from the current interval.

When inferring states during rescheduling, if calc_S < w[0], initialize the memory states using the first review.

>> What value is used for ivl in memory_state_from_sm2 when the interval is, say, 10 min? Is it 0.007 day?
>
> It's zero. And FSRS clamps it to 0.1 day.

@dae, can you confirm this? If it is so, things might need to be changed in order to implement my suggestions.

**Comment by L-M-Sherlock** [comment] 2023-11-25 11:00
In the case of the current issue, the revlog is empty when converting the memory state from sm2.

**Comment by user1823** [comment] 2023-11-25 11:08
> In the case of the current issue, the revlog is empty when converting the memory state from sm2.

Yes, all of the above discussion is about cards with empty revlog. What do you want to highlight here?

**Comment by L-M-Sherlock** [comment] 2023-11-26 02:26
> > And should a card with a non-zero interval and no review history/ease 2.5 be given a difficulty of 84%?
> 
> Technically, that is a separate issue and I was planning to give some more thought. But first, can you tell me what value for `ivl` is used in `memory_state_from_sm2` when the interval is, say, 10 min? Is it 0.007 day?

My bad. I misunderstand it. In that case, if the interval is 10 min, FSRS will clamp it to 0.1 day.

> I am ok with merging [ankitects/anki#2849](https://github.com/ankitects/anki/pull/2849) in, but is it the best solution? It's relying on the add-on to set the interval to 0 and not 1. And should a card with a non-zero interval and no review history/ease 2.5 be given a difficulty of 84%?

I recommend merging it. In the current issue, `Learn Now` card is just a new card. And a new card shouldn't have non-zero interval.

**Comment by dae** [comment] 2023-11-26 03:16
I've merged the PR in (thanks!), and will leave it up to you two to decide whether 84% is an appropriate difficulty for an ease of 2.5 (it seems rather high IMHO).

**Comment by L-M-Sherlock** [comment] 2023-11-26 03:34
> will leave it up to you two to decide whether 84% is an appropriate difficulty

In my test, it's 44%.

**Comment by user1823** [comment] 2023-11-26 03:45
Dae is talking about the case when interval is less than 1 day, but not zero.

I have proposed a (hacky) solution in https://github.com/open-spaced-repetition/fsrs4anki/issues/540#issuecomment-1826279693. What is your opinion on it?

**Comment by dae** [comment] 2023-11-26 04:46
@L-M-Sherlock I'm guessing you're testing with your PR branch and ivl=0, which treats the card as if it's new. What I'm focusing on is non-new cards. For example, a card with interval of 1 day and no revlog is given a difficulty of 75% when you press any of the buttons, despite the ease being 2.5. 10 days gives a difficulty of about 6.2, and 50 days gives a difficulty of about 50%

**Comment by L-M-Sherlock** [comment] 2023-11-26 04:59
> And should a card with a non-zero interval and no review history/ease 2.5 be given a difficulty of 84%

For (d=84%, s=0.1, r=0.9) and default parameters, the SInc is e^1.49 * (11 - 8.56) * 0.1^-0.14 * (e^(0.1*0.94) - 1) + 1 = 2.472950593. I think it's OK.

**Comment by user1823** [comment] 2023-11-26 05:36
@L-M-Sherlock, I think that you are right.

I (and probably Dae too) was thinking that because the D was high, it can cause the intervals to rise too slowly. But since the stability is also low, the SInc is not that low. In fact, the calculation of D is aimed at ensuring that SInc is roughly equal to the Ease.

Another problem I thought was that this high D can cause issues when the S becomes large eventually. But, the D can be decreased by mean reversion with subsequent reviews. So, this issue should not arise.

Currently, I have one point related to this issue worth pondering over:

Wouldn't it be better to use w[0] as the minimum value of stability in this function rather than the hard-coded value of 0.1?

My reasoning is that the stability of any card should not be lesser than the stability of a failed card.

**Comment by L-M-Sherlock** [comment] 2023-11-26 05:42
w[0] is the stability of a card that is forget in the first learning. If the card is forgot again and again in the subsequent reviews (not in the same day), the stability will decrease.

**Comment by user1823** [comment] 2023-11-26 05:54
Yes, you are right. I think that we can close this issue now.

@Exponent4806 @tatsumoto-ren, the next version of Anki will be fully compatible with this add-on. Until then, you can use the FSRS4Anki Helper add-on to reschedule the cards that were studied using the `Learn now` feature. This will correct the stability and difficulty of such cards.

The Helper add-on doesn't require any modification to be able to correct the memory states of these cards.

**Closed** 2023-11-26 06:05 UTC
Labels: question

**Comment by dae** [comment] 2023-12-04 03:25
Hmm, I think it might be worth having another think about this. Manually-scheduled cards have quite a different difficulty to normally-learnt cards, and the difficulty doesn't drop when they're reviewed again the next day. Could this be handled better?

https://forums.ankiweb.net/t/will-initial-manual-scheduling-interfere-with-fsrs/37976

**Comment by user1823** [comment] 2023-12-04 12:46
In this case, I think that Anki is calling `memory_state_from_sm2` at the second review because the Manual ratings are filtered out.

Possible solution:
If the first rating is Set Due Date (Manual rating & factor = 0), initialize memory states at the second rating (using normal formulas).

**Comment by dae** [comment] 2023-12-07 04:58
Basing it off the revlog is tricky, but it looks like we can achieve the same result by examining card.reps instead: https://github.com/ankitects/anki/commit/86aafa74a67dd06390b2bb0f7cb6ae9503152414

**Comment by dae** [comment] 2023-12-08 02:00
This, and the previous sm2/missing revlog hacks do apply when recalculating memory states - it is only training where they do not apply. My understanding is that @L-M-Sherlock is not particularly keen to add a bunch of extra special cases when training, but if you manage to convince him otherwise, perhaps we can revisit this in the future.

**Comment by L-M-Sherlock** [comment] 2023-12-08 12:22
> If the user has a habit of introducing new cards via Set Due Date

If the second revlog's type is learning, I will consider to include them. Otherwise, they are review cards instead of new cards, because we couldn't assume the user didn't learn the cards' contents before`Set Due Date` and didn't set different intervals based on their own grade system.

**Comment by dae** [comment] 2023-12-08 21:43
> I may be wrong, but I think that Anki doesn't store the reps count at the time of each review. So, if the card has already been reviewed, say, 5 times, then we can't know whether it had reps = 0 just before the second rating or not.

the new/reps=0/interval=0 path is only taken when FSRS doesn't have any usable revlogs for the card that could be used to infer the memory state.

**Comment by user1823** [comment] 2023-12-09 01:36
I think that we are not on the same page.

Consider the card in the linked Forums post (reproduced below). If it is rescheduled now, Anki will use the memory_state_from_sm2 function at the second rating. But, we want Anki to initialise memory states using the normal formulas at this rating.

<img width=500 src="https://global.discourse-cdn.com/business7/uploads/anki2/original/3X/c/2/c2c0047c5b16b5012b59fdb7833d6c7e98bdfce1.png">

**Comment by user1823** [comment] 2023-12-09 12:48
> we couldn't assume the user didn't learn the cards' contents beforeSet Due Date and didn't set different intervals based on their own grade system.

Yes, this is an important thing to consider (but only when training). So, let's not include these reviews in training for now. In the future, we can probably add another setting to control this.

The reason is simple: The users know how they use the Set Due Date option and, if informed appropriately, they can make a better decision to whether to include these reviews in training or not.

**Comment by L-M-Sherlock** [comment] 2023-12-09 13:36
Yeah. For example, the sm2 retention has already confused some users.

**Comment by siraben** [comment] 2023-12-10 00:44
I have numerous examples from my deck with manual scheduling and lots of reviews. If @L-M-Sherlock would like a copy, I would be glad to send it over email.

**Comment by siraben** [comment] 2023-12-10 00:46
The reason I use manual scheduling is for new cards that I would like to see over a period of time. You can select a group of cards without tagging and set due date to 1-7 to schedule it evenly over the next 7 days. Since it seems to interfere with FSRS, I've stopped using manual scheduling for now and manually tag and review by tagged cards instead.

**Comment by siraben** [comment] 2023-12-10 00:52
Here's another such card with manual setting. <img width="733" alt="Screenshot 2023-12-09 at 19 52 16" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/8219659/529710ba-0da7-44d0-92c4-ce3df5759145">

**Comment by user1823** [comment] 2023-12-10 02:04
@dae

In https://github.com/open-spaced-repetition/fsrs4anki/issues/557, @jcznk has demonstrated that the even in 23.12 beta 2, the memory states are not correct when such cards are rescheduled (as I mentioned in https://github.com/open-spaced-repetition/fsrs4anki/issues/540#issuecomment-1848074617).

So, I think that we should implement my idea, which is reproduced below with some modification:

If the first _few_ ratings are Manual, initialize memory states at the _first non-Manual rating_ (using normal formulas).
