### ISSUE TITLE
Different review count after rescheduling with helper addon

### ISSUE THREAD

**Issue by ImKamyar** [open-spaced-repetition/fsrs4anki#538] opened 2023-11-20 17:14 UTC
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Hello there, I recently noticed that when I hit the "Reschedule all cards" button in anki helper addon is usually decreases the amount of reviews that the initial scheduler has set me up to do.
For instance, today I had 38 reviews but when I pressed the button in anki helper, it became 28 all of a sudden. So I wanted to know whether I should hit the button daily since it decreases my review cards or just use it whenever I change my parameters and solely rely on the scheduler itself that is setup in the custom settings.**

**Comment by L-M-Sherlock** [comment] 2023-11-21 02:15
Could you share the collection before you hit "Reschedule all cards"? It will help me debug.

**Comment by L-M-Sherlock** [comment] 2023-11-21 02:17
By the way, which version of Anki do you use? The problem could be caused by fuzz, which has been fixed in Anki 23.10.1.

**Comment by ImKamyar** [comment] 2023-11-21 14:05
The version which I'm currectly using is 2.1.66.
Here is also the deck which I used: 
[Persian__Verses.zip](https://github.com/open-spaced-repetition/fsrs4anki/files/13427080/Persian__Verses.zip)
"w": [0.1, 0.1559, 0.3034, 0.473, 5.0482, 1.058, 0.9778, 0.0, 1.3725, 0.1, 0.8219, 2.0853, 0.1452, 0.2444, 1.1573, 0.1841, 2.61],
    "requestRetention": 0.75,
    "maximumInterval": 60,
I once tried the new Anki version but some addon were still not supported, does updating Anki fix the problem?

**Comment by L-M-Sherlock** [comment] 2023-11-21 15:33
> The version which I'm currectly using is 2.1.66.

I have stopped support of the add-on for this version.

By the way, do you enable load balance? It would also cause the issue.

**Comment by ImKamyar** [comment] 2023-11-21 16:01
Yeah I have load balance enabled, now that I think about it that's probably why it is like this.

**Closed** 2023-11-21 16:14 UTC
Labels: question
