### ISSUE TITLE
[Feature Request] generate w_i for each deck at once

### ISSUE THREAD

**Issue by ilya-rusyanov** [open-spaced-repetition/fsrs4anki#365] opened 2023-07-19 08:59 UTC
**Which module is related to your feature request?**
Optimizer

**Is your feature request related to a problem? Please describe.**
Currently user has to run the optimizer for each deck separately and copy/paste results into custom scheduler, while an '.apkg' file can contain multiple nested decks.

**Describe the solution you'd like**
The optimizer could output several values of w_i for each nested deck found in '.apkg' file, that would introduce more precise values per deck, especially for users who have whole deck hierarchy placed under single one (typically named 'all').

**Comment by user1823** [comment] 2023-07-19 09:50
Duplicate of https://github.com/open-spaced-repetition/fsrs4anki/issues/314

**Comment by user1823** [comment] 2023-07-23 06:20
Since this issue is a duplicate, I suggest you to close it.

**Closed** 2023-07-23 19:28 UTC
Labels: duplicate, enhancement
