### ISSUE TITLE
[BUG] Inconsistent intervals in version 2.1.58

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#161] opened 2023-02-21 16:25 UTC
**Describe the bug**
If I click "Show Answer" while reviewing a card, then go back to "Decks", then review the card again, I get different intervals. I don't think this was a problem before 2.1.58, or maybe I just didn't notice.
EDIT: I reverted back to 2.1.54 and yes, it works properly.
EDIT 2: nevermind, it doesn't work on 2.1.54, now I'm just really confused
![image](https://user-images.githubusercontent.com/83031600/220406252-fe8464b0-22b7-439a-86e9-5012e00d1e5b.png)
EDIT 3: ok, I deleted all Anki files and did a fresh installation of 2.1.55 (not 2.1.54) and I _think_ it works fine.
EDIT 4: I give up, I don't know what the hell is going on. Maybe after many re-installations I messed something up so bad that now every re-installation is broken.
![image](https://user-images.githubusercontent.com/83031600/220408594-d5c50d82-5930-4f66-a5ce-662f0bdd93e1.png)

**To Reproduce**
1. Review a card and click "Show Answer"
2. Don't click on answer buttons and click on "Decks" instead to cancel the review
3. Review that card again
4. See that intervals are different

**Expected behavior**
Intervals shouldn't change if I cancel a review and review again.

**Screenshots**
![image](https://user-images.githubusercontent.com/83031600/220402653-be530ca9-2064-434e-876f-774e6f3ad9be.png)

**Environment**
 - Anki version: 2.1.58, Qt 6.4.2, PyQt 6.4.0
 - OS: Windows 10
 - Scheduler version: v3.13.4

**Comment by Vitorvlv** [comment] 2023-02-21 18:11
' 2.1.54'

it never worked on 2.1.54, the feature needed for FSRS to work was only released in 2.1.55

' I get different intervals.'

Are we sure this isn't just fuzz acting? 

Try disabling it and checking again.

**Comment by Expertium** [comment] 2023-02-21 18:21
> it never worked on 2.1.54, the feature needed for FSRS to work was only released in 2.1.55

Oh yeah, right, I forgot. 

> Are we sure this isn't just fuzz acting?

Pretty damn sure.

**Comment by L-M-Sherlock** [comment] 2023-02-22 03:14
It is due to the async between scheduling and showing the interval. If the debug info is displayed normally, the interval applied is given by FSRS, even if the interval shown above the button is given by Anki's built-in algorithm. You can check the interval in `Previous card info`.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/32575846/220512028-51cc42b1-8739-4905-977f-ddd0c8eae091.png">

**Comment by Expertium** [comment] 2023-02-22 06:43
Is there any way to fix it permanently?

**Comment by L-M-Sherlock** [comment] 2023-02-22 07:48
> Is there any way to fix it permanently?

The way is outside of FSRS. By the way, I could only reproduce the bug in Image Occlusion cards. How about you?

**Comment by Expertium** [comment] 2023-02-22 08:13
Yeah, I just tested it on 2.1.55 and you're right, it seems to only affect Image Occlusion cards.

**Comment by L-M-Sherlock** [comment] 2023-02-26 11:20
I think this bug is not caused by FSRS, so I close this issue.

**Closed by L-M-Sherlock** 2023-02-26 11:20 UTC
Labels: bug
